using Microsoft.EntityFrameworkCore.Migrations;

namespace Template.Identity.Migrations
{
    public partial class RefreshToken_Key_AutoGenerated : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "01B168FE-810B-432D-9010-233BA0B380E9",
                column: "ConcurrencyStamp",
                value: "8a09f456-bc36-4f2b-ae0c-399f395ac6eb");

            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "2301D884-221A-4E7D-B509-0113DCC043E1",
                column: "ConcurrencyStamp",
                value: "6f3aeb5c-ab67-4e96-8a37-c3c7bc2b1b44");

            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "78A7570F-3CE5-48BA-9461-80283ED1D94D",
                column: "ConcurrencyStamp",
                value: "1113f398-4c60-4f4a-8d14-efb55a58d578");

            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "7D9B7113-A8F8-4035-99A7-A20DD400F6A3",
                column: "ConcurrencyStamp",
                value: "92e19c9c-7ace-4526-8de1-2a698af6197e");

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "9f93e84d-bcfe-4dab-9ba7-cb7065a63524",
                columns: new[] { "ConcurrencyStamp", "PasswordHash" },
                values: new object[] { "2b229ea7-ec00-42db-a286-7083b0938c61", "AQAAAAEAACcQAAAAEPnhm3XK5+bfE7DlpgeLK35KBUfGZVXXmpVaschJJFI2zCa4CA+OAI5MMzo6L1zrgw==" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "f1aafc30-5e54-4550-a5a1-4df0704b3258",
                columns: new[] { "ConcurrencyStamp", "PasswordHash" },
                values: new object[] { "8f777617-1fa0-4ee2-8a52-f503e7e78f7c", "AQAAAAEAACcQAAAAEOKWpqzAOB4ZdxLUAcEn0Qes9rV3H/A6w2ebHXzt6ZagebOqipcDRuZkYEIuD8E8VA==" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "01B168FE-810B-432D-9010-233BA0B380E9",
                column: "ConcurrencyStamp",
                value: "8bf86748-b1b2-46a6-b107-cf6edb30842c");

            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "2301D884-221A-4E7D-B509-0113DCC043E1",
                column: "ConcurrencyStamp",
                value: "49e18086-b9d0-4040-90ba-d6d44dc73937");

            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "78A7570F-3CE5-48BA-9461-80283ED1D94D",
                column: "ConcurrencyStamp",
                value: "1fb642a1-a688-440b-99d8-6317eda92ff3");

            migrationBuilder.UpdateData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "7D9B7113-A8F8-4035-99A7-A20DD400F6A3",
                column: "ConcurrencyStamp",
                value: "f8e0389e-9b6c-47f7-af9f-179f1864c2e5");

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "9f93e84d-bcfe-4dab-9ba7-cb7065a63524",
                columns: new[] { "ConcurrencyStamp", "PasswordHash" },
                values: new object[] { "94fd9e97-c6b4-407d-9984-3d1a258d6f54", "AQAAAAEAACcQAAAAEDAwWdB3CfwXL4D2leEwiyTLDgU+iagsaCP2vhZh4iKpRQf4Bipt+qFLVh+JFOZK6Q==" });

            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "f1aafc30-5e54-4550-a5a1-4df0704b3258",
                columns: new[] { "ConcurrencyStamp", "PasswordHash" },
                values: new object[] { "39e48427-d81e-4686-887f-f05fd08c73e7", "AQAAAAEAACcQAAAAEOKTb+NyPdJcvZPYg4pgqZDcG+2pLdxw/1IU4sJPSdM57GjBkPhy1PyJkeXAOzlGKw==" });
        }
    }
}
